### ISSUE TITLE
libhcnetsdk.so binary for ARM

### ISSUE THREAD

**Issue by nickaein** [shulianghe/new-project#1]
Hi,

I was looking for the Hikvision SDK binary libraries built for ARM processor (specifically `libhcnetsdk.so`) and encountered your repository. There is a `libhcnetsdk.so` there but it doesn't match ARM v7 (or I am missing something). 

I wanted to ask if you can help me on compiling libhcnetsdk for ARM (is the source code even available?) or whether you have different binary version of this library.

Thanks,

**Comment by shulianghe** [comment]
sorry for this, but you can ask Hik for help, i got it from Hik
